name: Test
on: 
  push:
    branches: [ main ]
jobs:
  Testing:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
          architecture: 'x64'
      - run: npm install -g node-gyp
      - run: npm install -g prebuildify
      - run: npm install
      - run: npm run test
